[mypy]
exclude=joblib_cache

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-ternary.*]
ignore_missing_imports = True

[mypy-shap.*]
ignore_missing_imports = True

[mypy-interpret.*]
ignore_missing_imports = True

[mypy-lime.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True

[mypy-sam2.*]
ignore_missing_imports = True

[mypy-cucim.*]
ignore_missing_imports = True

[mypy-cupy.*]
ignore_missing_imports = True

# ignore mypy errors associated with
# unmaintained legacy code in `neat_ml.lib`
[mypy-neat_ml.lib]
ignore_errors = True

[mypy-neat_ml.sample_scripts.ternary_examples.*]
ignore_errors = True

[mypy-neat_ml.tests.test_ternary.*]
ignore_errors = True
